const express=require('express'),helmet=require('helmet'),rateLimit=require('express-rate-limit'),jwt=require('jsonwebtoken'),fs=require('fs'),path=require('path'),multer=require('multer');
const app=express(),PORT=process.env.PORT||3000,ROOT=__dirname,DATA=path.join(ROOT,'data'),PUBLIC=path.join(ROOT,'public');
app.use(helmet({contentSecurityPolicy:false}));app.use(express.json({limit:'1mb'}));app.use(express.urlencoded({extended:true}));app.use(rateLimit({windowMs:15*60*1000,max:400}));app.use('/assets',express.static(path.join(PUBLIC,'assets')));app.use(express.static(PUBLIC));
const read=(f,d)=>{try{return JSON.parse(fs.readFileSync(path.join(DATA,f),'utf8'))}catch(e){return d}};const write=(f,d)=>fs.writeFileSync(path.join(DATA,f),JSON.stringify(d,null,2));
const SECRET=process.env.JWT_SECRET||'CHANGE_ME_IN_ENV',AU=process.env.ADMIN_USERNAME||'admin',AP=process.env.ADMIN_PASSWORD||'';
function auth(req,res,next){const t=(req.headers.authorization||'').replace(/^Bearer\s+/i,'');try{req.admin=jwt.verify(t,SECRET);next()}catch(e){res.status(401).json({error:'Authentication required'})}}
function dist(a,b,c,d){const R=6371,r=Math.PI/180,dl=(c-a)*r,dn=(d-b)*r,x=Math.sin(dl/2)**2+Math.cos(a*r)*Math.cos(c*r)*Math.sin(dn/2)**2;return R*2*Math.atan2(Math.sqrt(x),Math.sqrt(1-x))}
app.get('/api/config',(q,s)=>s.json({settings:read('settings.json',{}),menu:read('menu.json',[])}));
app.post('/api/location/check',(q,s)=>{const {lat,lng}=q.body||{},c=read('settings.json',{});const km=dist(c.base.lat,c.base.lng,+lat,+lng);if(!Number.isFinite(km))return s.status(400).json({error:'Valid location required'});if(km>c.delivery.maxRadiusKm)return s.json({allowed:false,cod:false,distanceKm:+km.toFixed(2),charge:null,message:`Delivery unavailable beyond ${c.delivery.maxRadiusKm} km.`});const cod=km<=c.delivery.codRadiusKm,charge=cod?0:Math.ceil(km)*c.delivery.ratePerKm;s.json({allowed:true,cod,distanceKm:+km.toFixed(2),charge,message:cod?'COD available in the COD zone.':'COD unavailable here. Online payment is required.'})});
app.post('/api/orders',(q,s)=>{try{const b=q.body||{},c=read('settings.json',{}),m=read('menu.json',[]);if(!b.name||!b.phone||!b.lat||!b.lng||!Array.isArray(b.items)||!b.items.length)return s.status(400).json({error:'Name, phone, location and cart are required.'});const km=dist(c.base.lat,c.base.lng,+b.lat,+b.lng);if(km>c.delivery.maxRadiusKm)return s.status(400).json({error:'Delivery area exceeded.'});let subtotal=0,pre=false;const items=b.items.map(i=>{const p=m.find(x=>x.id===i.id);if(!p)throw Error('Invalid item');const z=p.sizes[i.sizeIndex]||p.sizes[0],qty=Math.max(1,Math.min(100,+i.qty||1));pre ||= !!p.prebook;subtotal+=z[1]*qty;return{id:p.id,name:p.name,size:z[0],unitPrice:z[1],qty}});if((pre||km>c.delivery.codRadiusKm)&&!b.transactionId)return s.status(400).json({error:'Online payment transaction ID / last 5 digits is required.'});const delivery=km<=c.delivery.codRadiusKm?0:Math.ceil(km)*c.delivery.ratePerKm,o={id:'CSK-'+Date.now().toString(36).toUpperCase(),createdAt:new Date().toISOString(),status:'Pending',name:b.name,phone:b.phone,address:b.address||'',lat:+b.lat,lng:+b.lng,distanceKm:+km.toFixed(2),deliveryCharge:delivery,subtotal,total:subtotal+delivery,paymentMethod:b.paymentMethod||(pre||km>c.delivery.codRadiusKm?'bKash/Nagad':'COD'),transactionId:b.transactionId||'',deliveryTime:b.deliveryTime||'ASAP',items,prebook:pre,note:b.note||''};const os=read('orders.json',[]);os.unshift(o);write('orders.json',os);s.json({ok:true,order:o})}catch(e){s.status(400).json({error:e.message})}});
app.post('/api/reviews',(q,s)=>{const b=q.body||{};if(!b.name||!b.text)return s.status(400).json({error:'Name and review required'});const r=read('reviews.json',[]);const x={id:'R'+Date.now(),name:b.name,rating:Math.max(1,Math.min(5,+b.rating||5)),text:b.text,createdAt:new Date().toISOString(),approved:false};r.unshift(x);write('reviews.json',r);s.json({ok:true})});app.get('/api/reviews',(q,s)=>s.json(read('reviews.json',[])));
app.post('/api/admin/login',(q,s)=>{if(!AP)return s.status(503).json({error:'ADMIN_PASSWORD is not configured'});if(q.body.username!==AU||q.body.password!==AP)return s.status(401).json({error:'Invalid admin credentials'});s.json({token:jwt.sign({username:AU,role:'admin'},SECRET,{expiresIn:'8h'})})});
app.get('/api/admin/dashboard',auth,(q,s)=>{const o=read('orders.json',[]),r=read('reviews.json',[]),m=read('menu.json',[]);s.json({orders:o.length,pending:o.filter(x=>x.status==='Pending').length,delivered:o.filter(x=>x.status==='Delivered').length,revenue:o.filter(x=>x.status!=='Cancelled').reduce((a,x)=>a+x.total,0),menu:m.length,reviews:r.length})});
app.get('/api/orders',auth,(q,s)=>s.json(read('orders.json',[])));app.patch('/api/orders/:id',auth,(q,s)=>{const o=read('orders.json',[]),i=o.findIndex(x=>x.id===q.params.id);if(i<0)return s.status(404).json({error:'Not found'});if(q.body.status)o[i].status=q.body.status;write('orders.json',o);s.json(o[i])});
app.get('/api/admin/reviews',auth,(q,s)=>s.json(read('reviews.json',[])));app.patch('/api/admin/reviews/:id',auth,(q,s)=>{const r=read('reviews.json',[]),i=r.findIndex(x=>x.id===q.params.id);if(i<0)return s.status(404).json({error:'Not found'});r[i].approved=!!q.body.approved;write('reviews.json',r);s.json(r[i])});
app.put('/api/admin/settings',auth,(q,s)=>{const n={...read('settings.json',{}),...q.body};write('settings.json',n);s.json(n)});app.put('/api/admin/menu/:id',auth,(q,s)=>{const m=read('menu.json',[]),i=m.findIndex(x=>x.id===q.params.id);if(i<0)return s.status(404).json({error:'Not found'});m[i]={...m[i],...q.body};write('menu.json',m);s.json(m[i])});app.delete('/api/admin/menu/:id',auth,(q,s)=>{const m=read('menu.json',[]),n=m.filter(x=>x.id!==q.params.id);write('menu.json',n);s.json({ok:true})});
const up=multer({dest:path.join(PUBLIC,'assets')});app.post('/api/admin/upload',auth,up.single('image'),(q,s)=>{if(!q.file)return s.status(400).json({error:'No image'});const ext=path.extname(q.file.originalname)||'.jpg',name=Date.now()+ext,final=path.join(PUBLIC,'assets',name);fs.renameSync(q.file.path,final);s.json({url:'/assets/'+name})});
app.get('/admin',(q,s)=>s.sendFile(path.join(PUBLIC,'admin.html')));app.listen(PORT,()=>console.log('Chef Sifat Kitchen on '+PORT));
